#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ctypes
import pathlib
import re
import sys

OCTARINE_SCRIPTS = pathlib.Path("/home/ubuntu/ntt_Octarine/scripts")
sys.path.insert(0, str(OCTARINE_SCRIPTS))

from trace_bottom6_dilithium_layout import trace  # noqa: E402


BOTTOM6_BLOCKS = 2
BOTTOM6_BLOCK_STRIDE = 80
TOP1_WORDS = 1
TOP1_ZETA_OFFSET = 0
TOP1_QINV_OFFSET = TOP1_ZETA_OFFSET + TOP1_WORDS
BOTTOM6_ZETA_OFFSET = TOP1_QINV_OFFSET + TOP1_WORDS
BOTTOM6_QINV_OFFSET = BOTTOM6_ZETA_OFFSET + BOTTOM6_BLOCKS * BOTTOM6_BLOCK_STRIDE
PARAM_WORDS = BOTTOM6_QINV_OFFSET + BOTTOM6_BLOCKS * BOTTOM6_BLOCK_STRIDE


def parse_array(text: str, name: str) -> list[int]:
    pattern = rf"#define\s+{re.escape(name)}\s*\{{(.*?)\}}"
    match = re.search(pattern, text, re.S)
    if not match:
        raise SystemExit(f"could not find {name}")
    body = match.group(1)
    return [int(tok, 0) for tok in re.findall(r"[-+]?(?:0x[0-9a-fA-F]+|\d+)", body)]


def parse_macro(text: str, name: str) -> int:
    pattern = rf"#define\s+{re.escape(name)}\s*\((0x[0-9a-fA-F]+|\d+)\)"
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"could not find {name}")
    return int(match.group(1), 0)


def to_i32(value: int) -> int:
    return ctypes.c_int32(value & 0xFFFFFFFF).value


def k_for(block: int, level: int, r: int) -> int:
    base = {4: 2, 5: 4, 6: 8, 7: 16, 8: 32, 9: 64}[level]
    scale = {4: 1, 5: 2, 6: 4, 7: 8, 8: 16, 9: 32}[level]
    return base + scale * block + r


def root_vectors_for_block(block: int) -> tuple[list[int], list[str]]:
    records, _final = trace()
    layout: list[int] = []
    comments: list[str] = []

    def append_vector(level: int, vector_rs: list[int], label: str) -> None:
        if len(vector_rs) != 8:
            raise SystemExit(f"{label}: expected 8 lanes, got {len(vector_rs)}")
        ks = [k_for(block, level, r) for r in vector_rs]
        layout.extend(ks)
        comments.append(f"block {block} {label}: " + ", ".join(str(k) for k in ks))

    append_vector(4, list(records[0].r), "L1")
    append_vector(5, list(next(r for r in records if r.level == 5).r), "L2")
    append_vector(6, list(next(r for r in records if r.level == 6).r), "L3")
    append_vector(7, list(next(r for r in records if r.level == 7).r), "L4")

    l8 = [r for r in records if r.level == 8]
    append_vector(8, list(l8[0].r), "L5a")
    append_vector(8, list(l8[2].r), "L5b")

    for idx, rec in enumerate(r for r in records if r.level == 9):
        append_vector(9, list(rec.r), f"L6{idx}")

    expected = set()
    for level, count in ((4, 1), (5, 2), (6, 4), (7, 8), (8, 16), (9, 32)):
        expected.update(k_for(block, level, r) for r in range(count))
    used = set(layout)
    if len(layout) != BOTTOM6_BLOCK_STRIDE:
        raise SystemExit(f"block {block}: expected {BOTTOM6_BLOCK_STRIDE} slots, got {len(layout)}")
    if used != expected:
        raise SystemExit(f"block {block}: k mismatch missing={sorted(expected - used)} extra={sorted(used - expected)}")
    return layout, comments


def build_bottom6_layout(zetas: list[int]) -> tuple[list[int], list[str]]:
    out: list[int] = []
    comments: list[str] = []
    for block in range(BOTTOM6_BLOCKS):
        ks, block_comments = root_vectors_for_block(block)
        out.extend(zetas[k] for k in ks)
        comments.extend(block_comments)
    if len(out) != BOTTOM6_BLOCKS * BOTTOM6_BLOCK_STRIDE:
        raise SystemExit(f"unexpected bottom6 table length {len(out)}")
    return out, comments


def format_array(name: str, values: list[int], length_expr: str) -> list[str]:
    lines = [f"static const int32_t {name}[{length_expr}] __attribute__((aligned(32))) = {{"]
    for i in range(0, len(values), 8):
        lines.append("  " + ", ".join(str(v) for v in values[i:i + 8]) + ",")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    text = pathlib.Path(args.input).read_text()
    zetas = parse_array(text, "RRLWR_KEM_ZETAS")
    primeinv = parse_macro(text, "RRLWR_PKE_PRIMEINV")
    zetas_qinv = [to_i32((z & 0xFFFFFFFF) * (primeinv & 0xFFFFFFFF)) for z in zetas]

    bottom6_zetas, comments = build_bottom6_layout(zetas)
    bottom6_qinv, _ = build_bottom6_layout(zetas_qinv)
    table = [zetas[1], zetas_qinv[1]]
    table.extend(bottom6_zetas)
    table.extend(bottom6_qinv)
    if len(table) != PARAM_WORDS:
        raise SystemExit(f"unexpected table length {len(table)} != {PARAM_WORDS}")

    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/gen_ntt_param.py */")
    lines.append("#ifndef NTT_PARAM_H")
    lines.append("#define NTT_PARAM_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include \"parameters.h\"")
    lines.append("")
    lines.append(f"#define NTT_AVX_PARAM_TOP1_ZETA_OFFSET {TOP1_ZETA_OFFSET}")
    lines.append(f"#define NTT_AVX_PARAM_TOP1_QINV_OFFSET {TOP1_QINV_OFFSET}")
    lines.append(f"#define NTT_AVX_PARAM_BOTTOM6_ZETA_OFFSET {BOTTOM6_ZETA_OFFSET}")
    lines.append(f"#define NTT_AVX_PARAM_BOTTOM6_QINV_OFFSET {BOTTOM6_QINV_OFFSET}")
    lines.append(f"#define NTT_AVX_PARAM_BOTTOM6_BLOCK_STRIDE {BOTTOM6_BLOCK_STRIDE}")
    lines.append(f"#define NTT_AVX_PARAM_WORDS {PARAM_WORDS}")
    lines.append("")
    lines.append("/* Bottom6 source-k mapping, 80 int32 slots per 64-coeff block:")
    for comment in comments:
        lines.append(f" * {comment}")
    lines.append(" */")
    lines.append("")
    lines.extend(format_array("RRLWR_KEM_ZETAS_QINV", zetas_qinv, "RRLWR_N"))
    lines.append("")
    lines.extend(format_array("RRLWR_KEM_NTT_AVX_PARAMS", table, "NTT_AVX_PARAM_WORDS"))
    lines.append("")
    lines.append("#endif")
    lines.append("")

    pathlib.Path(args.output).write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
