#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ctypes
import pathlib
import re
import sys


def parse_array(text: str, name: str) -> list[int]:
    pattern = rf"#define\s+{re.escape(name)}\s*\{{(.*?)\}}"
    match = re.search(pattern, text, re.S)
    if not match:
        raise SystemExit(f"could not find {name} in the input header")
    return [int(tok, 0) for tok in re.findall(r"[-+]?(?:0x[0-9a-fA-F]+|\d+)", match.group(1))]


def parse_macro(text: str, name: str) -> int:
    pattern = rf"#define\s+{re.escape(name)}\s*\((0x[0-9a-fA-F]+|\d+)\)"
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"could not find {name} in the input header")
    return int(match.group(1), 0)


def to_i32(value: int) -> int:
    return ctypes.c_int32(value & 0xFFFFFFFF).value


def mul32(a: int, b: int) -> int:
    return to_i32((a & 0xFFFFFFFF) * (b & 0xFFFFFFFF))


def reverse_with_padding(values: list[int]) -> list[int]:
    out = [0] * len(values)
    for i in range(len(values) - 1):
        out[i] = values[len(values) - 1 - i]
    out[-1] = 0
    return out


def format_array(name: str, values: list[int]) -> list[str]:
    lines = [f"static const int32_t {name}[RRLWR_N] __attribute__((aligned(32))) = {{"]
    for i in range(0, len(values), 8):
        lines.append("  " + ", ".join(str(v) for v in values[i : i + 8]) + ",")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    return lines


def emit_sign(text: str) -> str:
    zetas1 = parse_array(text, "RRLWR_SIGN_ZETAS1")
    zetas2 = parse_array(text, "RRLWR_SIGN_ZETAS2")
    prime1inv = parse_macro(text, "RRLWR_SIGN_PRIME1INV")
    prime2inv = parse_macro(text, "RRLWR_SIGN_PRIME2INV")
    finalconst1 = parse_macro(text, "RRLWR_SIGN_NTTINV_FINALCONST1")
    finalconst2 = parse_macro(text, "RRLWR_SIGN_NTTINV_FINALCONST2")

    zetas1_intt = reverse_with_padding(zetas1)
    zetas2_intt = reverse_with_padding(zetas2)
    zetas1_pre = [mul32(v, prime1inv) for v in zetas1_intt]
    zetas2_pre = [mul32(v, prime2inv) for v in zetas2_intt]
    finalconst1_pre = mul32(finalconst1, prime1inv)
    finalconst2_pre = mul32(finalconst2, prime2inv)

    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/gen_intt_precalcu_zetas.py */")
    lines.append("#ifndef INTT_PRECALCU_TABLES_H")
    lines.append("#define INTT_PRECALCU_TABLES_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include \"parameters.h\"")
    lines.append("")
    lines.append(f"#define RRLWR_SIGN_NTTINV_FINALCONST1_PRE ({finalconst1_pre})")
    lines.append(f"#define RRLWR_SIGN_NTTINV_FINALCONST2_PRE ({finalconst2_pre})")
    lines.append("")
    lines.extend(format_array("RRLWR_SIGN_ZETAS1_INTT", zetas1_intt))
    lines.append("")
    lines.extend(format_array("RRLWR_SIGN_ZETAS1_INTT_PRE", zetas1_pre))
    lines.append("")
    lines.extend(format_array("RRLWR_SIGN_ZETAS2_INTT", zetas2_intt))
    lines.append("")
    lines.extend(format_array("RRLWR_SIGN_ZETAS2_INTT_PRE", zetas2_pre))
    lines.append("")
    lines.append("#endif")
    lines.append("")
    return "\n".join(lines)


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    text = pathlib.Path(args.input).read_text()
    if "#define RRLWR_SIGN_ZETAS1" not in text or "#define RRLWR_SIGN_ZETAS2" not in text:
      raise SystemExit("this script currently expects the SIGN parameters header")

    pathlib.Path(args.output).write_text(emit_sign(text))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
