#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ctypes
import pathlib
import re


def parse_array(text: str, name: str) -> list[int]:
    pattern = rf"static\s+const\s+int32_t\s+{re.escape(name)}\s*\[RRLWR_N\].*?=\s*\{{(.*?)\}};"
    match = re.search(pattern, text, re.S)
    if not match:
        raise SystemExit(f"could not find {name} in input header")
    return [int(tok, 0) for tok in re.findall(r"[-+]?(?:0x[0-9a-fA-F]+|\d+)", match.group(1))]


def parse_macro(text: str, name: str) -> int:
    pattern = rf"#define\s+{re.escape(name)}\s*\(([-+]?(?:0x[0-9a-fA-F]+|\d+))\)"
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"could not find {name} in parameters header")
    return int(match.group(1), 0)


def to_i32(value: int) -> int:
    return ctypes.c_int32(value & 0xFFFFFFFF).value


def mul32(a: int, b: int) -> int:
    return to_i32((a & 0xFFFFFFFF) * (b & 0xFFFFFFFF))


def montgomery_mul32_precalcu(a: int, b: int, b_pre: int, prime: int) -> int:
    prod = ctypes.c_int64(a * b).value
    t = to_i32((a & 0xFFFFFFFF) * (b_pre & 0xFFFFFFFF))
    s = ctypes.c_int64(prod + t * prime).value
    return to_i32(s >> 32)


def format_array(name: str, values: list[int]) -> list[str]:
    lines = [f"static const int32_t {name}[RRLWR_N] __attribute__((aligned(32))) = {{"]
    for i in range(0, len(values), 8):
        lines.append("  " + ", ".join(str(v) for v in values[i : i + 8]) + ",")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    return lines


def make_fused(label: str,
               zetas: list[int],
               zetas_pre: list[int],
               prime: int,
               primeinv: int,
               finalconst: int) -> tuple[list[int], list[int], str]:
    fused = list(zetas)
    fused_pre = list(zetas_pre)
    last_k = len(zetas) - 2
    finalconst_pre = mul32(finalconst, primeinv)
    fused_zeta = montgomery_mul32_precalcu(zetas[last_k], finalconst, finalconst_pre, prime)
    fused_zeta_pre = mul32(fused_zeta, primeinv)
    fused[last_k] = fused_zeta
    fused_pre[last_k] = fused_zeta_pre
    info = (
        f"{label}: last_k={last_k} zeta={zetas[last_k]} "
        f"finalconst={finalconst} finalconst_pre={finalconst_pre} "
        f"fused_zeta={fused_zeta} fused_zeta_pre={fused_zeta_pre}"
    )
    return fused, fused_pre, info


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--precalcu", required=True)
    parser.add_argument("--parameters", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    precalcu_text = pathlib.Path(args.precalcu).read_text()
    params_text = pathlib.Path(args.parameters).read_text()

    zetas1 = parse_array(precalcu_text, "RRLWR_SIGN_ZETAS1_INTT")
    zetas1_pre = parse_array(precalcu_text, "RRLWR_SIGN_ZETAS1_INTT_PRE")
    zetas2 = parse_array(precalcu_text, "RRLWR_SIGN_ZETAS2_INTT")
    zetas2_pre = parse_array(precalcu_text, "RRLWR_SIGN_ZETAS2_INTT_PRE")

    prime1 = parse_macro(params_text, "RRLWR_SIGN_PRIME1")
    prime1inv = parse_macro(params_text, "RRLWR_SIGN_PRIME1INV")
    finalconst1 = parse_macro(params_text, "RRLWR_SIGN_NTTINV_FINALCONST1")
    prime2 = parse_macro(params_text, "RRLWR_SIGN_PRIME2")
    prime2inv = parse_macro(params_text, "RRLWR_SIGN_PRIME2INV")
    finalconst2 = parse_macro(params_text, "RRLWR_SIGN_NTTINV_FINALCONST2")

    fused1, fused1_pre, info1 = make_fused("prime1", zetas1, zetas1_pre, prime1, prime1inv, finalconst1)
    fused2, fused2_pre, info2 = make_fused("prime2", zetas2, zetas2_pre, prime2, prime2inv, finalconst2)

    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/gen_intt_final_fused_zetas.py */")
    lines.append("#ifndef INTT_FINAL_FUSED_TABLES_H")
    lines.append("#define INTT_FINAL_FUSED_TABLES_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include \"parameters.h\"")
    lines.append("")
    lines.extend(format_array("RRLWR_SIGN_ZETAS1_INTT_FINALFUSED", fused1))
    lines.append("")
    lines.extend(format_array("RRLWR_SIGN_ZETAS1_INTT_FINALFUSED_PRE", fused1_pre))
    lines.append("")
    lines.extend(format_array("RRLWR_SIGN_ZETAS2_INTT_FINALFUSED", fused2))
    lines.append("")
    lines.extend(format_array("RRLWR_SIGN_ZETAS2_INTT_FINALFUSED_PRE", fused2_pre))
    lines.append("")
    lines.append("#endif")
    lines.append("")
    pathlib.Path(args.output).write_text("\n".join(lines))

    print(info1)
    print(info2)
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
