#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ctypes
import pathlib
import re


def parse_array(text: str, name: str) -> list[int]:
    pattern = rf"#define\s+{re.escape(name)}\s*\{{(.*?)\}}"
    match = re.search(pattern, text, re.S)
    if not match:
        raise SystemExit(f"could not find {name} in the input header")
    return [int(tok, 0) for tok in re.findall(r"[-+]?(?:0x[0-9a-fA-F]+|\d+)", match.group(1))]


def parse_macro(text: str, name: str) -> int:
    pattern = rf"#define\s+{re.escape(name)}\s*\((0x[0-9a-fA-F]+|\d+)\)"
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"could not find {name} in the input header")
    return int(match.group(1), 0)


def to_i32(value: int) -> int:
    return ctypes.c_int32(value & 0xFFFFFFFF).value


def mul32(a: int, b: int) -> int:
    return to_i32((a & 0xFFFFFFFF) * (b & 0xFFFFFFFF))


def reverse_with_padding(values: list[int]) -> list[int]:
    out = [0] * len(values)
    for i in range(len(values) - 1):
        out[i] = values[len(values) - 1 - i]
    out[-1] = 0
    return out


def format_array(name: str, values: list[int]) -> list[str]:
    lines = [f"static const int32_t {name}[RRLWR_N] __attribute__((aligned(32))) = {{"]
    for i in range(0, len(values), 8):
        lines.append("  " + ", ".join(str(v) for v in values[i : i + 8]) + ",")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    text = pathlib.Path(args.input).read_text()
    zetas = parse_array(text, "RRLWR_KEM_ZETAS")
    primeinv = parse_macro(text, "RRLWR_PKE_PRIMEINV")
    finalconst = parse_macro(text, "RRLWR_NTTINV_FINALCONST")
    finalconst_pre = mul32(finalconst, primeinv)

    zetas_intt = reverse_with_padding(zetas)
    zetas_pre = [mul32(v, primeinv) for v in zetas_intt]

    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/gen_intt_precalcu_tables.py */")
    lines.append("#ifndef INTT_PRECALCU_TABLES_H")
    lines.append("#define INTT_PRECALCU_TABLES_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include \"parameters.h\"")
    lines.append("")
    lines.append(f"#define RRLWR_KEM_NTTINV_FINALCONST_PRE ({finalconst_pre})")
    lines.append("")
    lines.extend(format_array("RRLWR_KEM_ZETAS_INTT", zetas_intt))
    lines.append("")
    lines.extend(format_array("RRLWR_KEM_ZETAS_INTT_PRE", zetas_pre))
    lines.append("")
    lines.append("#endif")
    lines.append("")

    pathlib.Path(args.output).write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
