#!/usr/bin/env python3
import argparse
import ctypes
import pathlib
import re


BLOCKS = 16
BLOCK_STRIDE = 64


def parse_array(text: str, name: str):
    pattern = rf"#define\s+{re.escape(name)}\s*\{{(.*?)\}}"
    match = re.search(pattern, text, re.S)
    if not match:
        raise SystemExit(f"could not find {name}")
    body = match.group(1)
    tokens = re.findall(r"[-+]?(?:0x[0-9a-fA-F]+|\d+)", body)
    return [int(tok, 0) for tok in tokens]


def parse_macro(text: str, name: str):
    pattern = rf"#define\s+{re.escape(name)}\s*\((0x[0-9a-fA-F]+|\d+)\)"
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"could not find {name}")
    return int(match.group(1), 0)


def to_i32(value: int) -> int:
    return ctypes.c_int32(value & 0xffffffff).value


def build_block_layout(zetas):
    layout = []
    for b in range(BLOCKS):
        roots = []
        roots.append(zetas[16 + b])
        roots.extend(zetas[32 + 2 * b + r] for r in range(2))
        roots.extend(zetas[64 + 4 * b + r] for r in range(4))
        roots.extend(zetas[128 + 8 * b + r] for r in range(8))
        roots.extend(zetas[256 + 16 * b + r] for r in range(16))
        roots.extend(zetas[512 + 32 * b + r] for r in range(32))
        if len(roots) != 63:
            raise SystemExit(f"unexpected block root count {len(roots)}")
        roots.append(0)
        layout.extend(roots)
    if len(layout) != BLOCKS * BLOCK_STRIDE:
        raise SystemExit(f"unexpected layout length {len(layout)}")
    return layout


def format_array(name: str, values):
    lines = [f"static const int32_t {name}[NTT1024_BOT6_AVX2_BLOCK_STRIDE * {BLOCKS}] = {{"]
    for i in range(0, len(values), 8):
        chunk = ", ".join(str(v) for v in values[i:i + 8])
        lines.append(f"  {chunk},")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    return lines


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    text = pathlib.Path(args.input).read_text()
    zetas1 = parse_array(text, "RRLWR_SIGN_ZETAS1")
    zetas2 = parse_array(text, "RRLWR_SIGN_ZETAS2")
    prime1inv = parse_macro(text, "RRLWR_SIGN_PRIME1INV")
    prime2inv = parse_macro(text, "RRLWR_SIGN_PRIME2INV")

    zetas1_pre = [to_i32((z & 0xffffffff) * (prime1inv & 0xffffffff)) for z in zetas1]
    zetas2_pre = [to_i32((z & 0xffffffff) * (prime2inv & 0xffffffff)) for z in zetas2]

    out = []
    out.append("/* Auto-generated by scripts/gen_ntt1024_bot6_avx2_zetas.py */")
    out.append("#ifndef NTT1024_BOT6_AVX2_ZETAS_H")
    out.append("#define NTT1024_BOT6_AVX2_ZETAS_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("#include \"parameters.h\"")
    out.append("")
    out.append("#define NTT1024_BOT6_AVX2_BLOCK_STRIDE 64")
    out.append("")
    out.extend(format_array("RRLWR_SIGN_ZETAS1_BOT6_AVX2", build_block_layout(zetas1)))
    out.append("")
    out.extend(format_array("RRLWR_SIGN_ZETAS1_PRE_BOT6_AVX2", build_block_layout(zetas1_pre)))
    out.append("")
    out.extend(format_array("RRLWR_SIGN_ZETAS2_BOT6_AVX2", build_block_layout(zetas2)))
    out.append("")
    out.extend(format_array("RRLWR_SIGN_ZETAS2_PRE_BOT6_AVX2", build_block_layout(zetas2_pre)))
    out.append("")
    out.append("#endif")
    out.append("")

    pathlib.Path(args.output).write_text("\n".join(out))


if __name__ == "__main__":
    main()
