#!/usr/bin/env python3
from __future__ import annotations

import argparse
import ctypes
import pathlib
import re
import sys

SCRIPT_DIR = pathlib.Path(__file__).resolve().parent
sys.path.insert(0, str(SCRIPT_DIR))

from gen_ntt1024_bot6_dilithium_zetas import build_layout  # noqa: E402


TOPMID_WORDS = 16
BOT6_WORDS = 16 * 80
TOPMID_ZETAS_OFFSET = 0
TOPMID_PRE_OFFSET = TOPMID_ZETAS_OFFSET + TOPMID_WORDS
BOT6_ZETAS_OFFSET = TOPMID_PRE_OFFSET + TOPMID_WORDS
BOT6_PRE_OFFSET = BOT6_ZETAS_OFFSET + BOT6_WORDS
PARAM_WORDS = BOT6_PRE_OFFSET + BOT6_WORDS


def parse_array(text: str, name: str) -> list[int]:
    pattern = rf"#define\s+{re.escape(name)}\s*\{{(.*?)\}}"
    match = re.search(pattern, text, re.S)
    if not match:
        raise SystemExit(f"could not find {name}; pass the header containing this macro via --input")
    return [int(tok, 0) for tok in re.findall(r"[-+]?(?:0x[0-9a-fA-F]+|\d+)", match.group(1))]


def parse_macro(text: str, name: str) -> int:
    pattern = rf"#define\s+{re.escape(name)}\s*\((0x[0-9a-fA-F]+|\d+)\)"
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"could not find {name}; pass the header containing this macro via --input")
    return int(match.group(1), 0)


def to_i32(value: int) -> int:
    return ctypes.c_int32(value & 0xFFFFFFFF).value


def build_param_table(zetas: list[int], primeinv: int) -> list[int]:
    zetas_pre = [to_i32((z & 0xFFFFFFFF) * (primeinv & 0xFFFFFFFF)) for z in zetas]
    bot6_zetas, _ = build_layout(zetas)
    bot6_pre, _ = build_layout(zetas_pre)
    table: list[int] = []
    table.extend(zetas[:TOPMID_WORDS])
    table.extend(zetas_pre[:TOPMID_WORDS])
    table.extend(bot6_zetas)
    table.extend(bot6_pre)
    if len(table) != PARAM_WORDS:
        raise SystemExit(f"unexpected param words {len(table)} != {PARAM_WORDS}")
    return table


def format_array(name: str, values: list[int]) -> list[str]:
    lines = [f"static const int32_t {name}[NTT_AVX_PARAM_WORDS] __attribute__((aligned(32))) = {{"]
    for i in range(0, len(values), 8):
        lines.append("  " + ", ".join(str(v) for v in values[i:i + 8]) + ",")
    lines[-1] = lines[-1].rstrip(",")
    lines.append("};")
    return lines


def main() -> int:
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    text = pathlib.Path(args.input).read_text()
    zetas1 = parse_array(text, "RRLWR_SIGN_ZETAS1")
    zetas2 = parse_array(text, "RRLWR_SIGN_ZETAS2")
    prime1inv = parse_macro(text, "RRLWR_SIGN_PRIME1INV")
    prime2inv = parse_macro(text, "RRLWR_SIGN_PRIME2INV")

    table1 = build_param_table(zetas1, prime1inv)
    table2 = build_param_table(zetas2, prime2inv)

    lines: list[str] = []
    lines.append("/* Auto-generated by scripts/gen_ntt_param.py */")
    lines.append("#ifndef NTT_PARAM_H")
    lines.append("#define NTT_PARAM_H")
    lines.append("")
    lines.append("#include <stdint.h>")
    lines.append("#include \"parameters.h\"")
    lines.append("")
    lines.append("#define NTT_AVX_PARAM_TOPMID_ZETAS_OFFSET 0")
    lines.append("#define NTT_AVX_PARAM_TOPMID_PRE_OFFSET 16")
    lines.append("#define NTT_AVX_PARAM_BOT6_ZETAS_OFFSET 32")
    lines.append("#define NTT_AVX_PARAM_BOT6_PRE_OFFSET 1312")
    lines.append("#define NTT_AVX_PARAM_BOT6_BLOCK_STRIDE 80")
    lines.append("#define NTT_AVX_PARAM_WORDS 2592")
    lines.append("")
    lines.append("/* Layout, in int32_t words:")
    lines.append(" *   [0, 16)       L0-L3 scalar zetas, k=0..15")
    lines.append(" *   [16, 32)      L0-L3 scalar pre values, k=0..15")
    lines.append(" *   [32, 1312)    L4-L9 reordered bottom6 zetas, 16 blocks * stride 80")
    lines.append(" *   [1312, 2592)  L4-L9 reordered bottom6 pre values, same lane mapping")
    lines.append(" */")
    lines.append("")
    lines.extend(format_array("RRLWR_SIGN_NTT_AVX_PARAMS1", table1))
    lines.append("")
    lines.extend(format_array("RRLWR_SIGN_NTT_AVX_PARAMS2", table2))
    lines.append("")
    lines.append("#endif")
    lines.append("")

    pathlib.Path(args.output).write_text("\n".join(lines))
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
