#!/usr/bin/env python3
import argparse
import ctypes
import pathlib
import re
import sys


def parse_array(text: str, name: str):
    pattern = rf"#define\s+{re.escape(name)}\s*\{{(.*?)\}}"
    match = re.search(pattern, text, re.S)
    if not match:
      raise SystemExit(f"could not find {name}")
    body = match.group(1)
    tokens = re.findall(r"[-+]?(?:0x[0-9a-fA-F]+|\d+)", body)
    return [int(tok, 0) for tok in tokens]


def parse_macro(text: str, name: str):
    pattern = rf"#define\s+{re.escape(name)}\s*\((0x[0-9a-fA-F]+|\d+)\)"
    match = re.search(pattern, text)
    if not match:
        raise SystemExit(f"could not find {name}")
    return int(match.group(1), 0)


def to_i32(u32_value: int) -> int:
    return ctypes.c_int32(u32_value & 0xffffffff).value


def format_array(name: str, values):
    lines = []
    for i in range(0, len(values), 8):
        chunk = ", ".join(str(v) for v in values[i:i + 8])
        lines.append(f"  {chunk},")
    lines[-1] = lines[-1].rstrip(",")
    return [f"static const int32_t {name}[RRLWR_N] = {{"] + lines + ["};"]


def main():
    parser = argparse.ArgumentParser()
    parser.add_argument("--input", required=True)
    parser.add_argument("--output", required=True)
    args = parser.parse_args()

    input_path = pathlib.Path(args.input)
    output_path = pathlib.Path(args.output)
    text = input_path.read_text()

    zetas1 = parse_array(text, "RRLWR_SIGN_ZETAS1")
    zetas2 = parse_array(text, "RRLWR_SIGN_ZETAS2")
    prime1 = parse_macro(text, "RRLWR_SIGN_PRIME1")
    prime2 = parse_macro(text, "RRLWR_SIGN_PRIME2")
    prime1inv = parse_macro(text, "RRLWR_SIGN_PRIME1INV")
    prime2inv = parse_macro(text, "RRLWR_SIGN_PRIME2INV")

    zetas1_pre = [to_i32((z & 0xffffffff) * (prime1inv & 0xffffffff)) for z in zetas1]
    zetas2_pre = [to_i32((z & 0xffffffff) * (prime2inv & 0xffffffff)) for z in zetas2]

    if len(zetas1_pre) != len(zetas1) or len(zetas2_pre) != len(zetas2):
        raise SystemExit("unexpected zeta length")

    out = []
    out.append("/* Auto-generated by scripts/gen_zetas_pre.py */")
    out.append("#ifndef RRLWR_ZETAS_PRE_H")
    out.append("#define RRLWR_ZETAS_PRE_H")
    out.append("")
    out.append("#include <stdint.h>")
    out.append("#include \"parameters.h\"")
    out.append("")
    out.extend(format_array("RRLWR_SIGN_ZETAS1_pre", zetas1_pre))
    out.append("")
    out.extend(format_array("RRLWR_SIGN_ZETAS2_pre", zetas2_pre))
    out.append("")
    out.append("#endif")
    out.append("")

    output_path.write_text("\n".join(out))


if __name__ == "__main__":
    main()
